version: '3'
services:
  wallet:
    image: juanluisbaptiste/bitcoin-wallet:latest
    container_name: bitcoin-wallet
       environment:
      - ENABLE_WEB_VIEW=yes
      - DISPLAY=unix$DISPLAY
      - DEBUG=yes
      - USER_UID=1026
    network_mode: host
    # ports:
    #  - "10000:10000"
  wallet-data:
    image: juanluisbaptiste/bitcoin-wallet:latest
    container_name: wallet-data
    volumes:
    -  /tmp/.X11-unix:/tmp/.X11-unix
    - /etc/localtime:/etc/localtime:ro
    command: /bin/true
